import JSZip from 'jszip';
import crypto from 'node:crypto';
import { ExportManifest, ManifestFileEntry } from './types';

export interface ZipPackageInput {
  baseName: string;
  manifest: ExportManifest;
  jsonBuffer?: Buffer;
  pdfBuffer?: Buffer;
  excelBuffer?: Buffer;
}

export interface ReportItemEntry {
  reportType: string;
  title: string;
  pdfBuffer?: Buffer;
  excelBuffer?: Buffer;
}

export interface FullReportZipInput {
  baseName: string;
  scope: 'SITE' | 'ALL_SITES';
  siteName?: string;
  siteCode?: string;
  siteId?: string;
  period: {
    preset: string;
    from?: string | null;
    to?: string | null;
    label: string;
  };
  generatedBy: {
    id: string;
    username: string;
    role: string;
  };
  reports: ReportItemEntry[];
}

/**
 * Creates a verified, reports-only ZIP package containing human-readable
 * analytical outputs (PDFs, Excel spreadsheets, metadata manifest, README).
 * Strictly contains NO raw database JSON dumps, NO SQLite DB, NO recovery datasets.
 */
export async function createFullReportZip(input: FullReportZipInput): Promise<Buffer> {
  const zip = new JSZip();
  const fileEntries: ManifestFileEntry[] = [];
  let pdfCount = 0;
  let excelCount = 0;

  for (const report of input.reports) {
    const safeTitle = report.title.replace(/[^a-zA-Z0-9_\-]/g, '_');

    if (report.pdfBuffer) {
      const pdfPath = `reports/${safeTitle}.pdf`;
      zip.file(pdfPath, report.pdfBuffer);
      const sha256 = crypto.createHash('sha256').update(report.pdfBuffer).digest('hex');
      fileEntries.push({
        path: pdfPath,
        format: 'PDF',
        bytes: report.pdfBuffer.length,
        sha256,
      });
      pdfCount++;
    }

    if (report.excelBuffer) {
      const excelPath = `reports/${safeTitle}.xlsx`;
      zip.file(excelPath, report.excelBuffer);
      const sha256 = crypto.createHash('sha256').update(report.excelBuffer).digest('hex');
      fileEntries.push({
        path: excelPath,
        format: 'XLSX',
        bytes: report.excelBuffer.length,
        sha256,
      });
      excelCount++;
    }
  }

  // README.txt
  const readmeLines = [
    '================================================================================',
    'AB CONSTRUCTIONS & INTERIORS — SITE WORK REPORT ARCHIVE',
    '================================================================================',
    '',
    `Application:      SITE WORK Enterprise System`,
    `Package Type:     REPORT_PACKAGE (Human-Readable Analytical Reports Only)`,
    `Generated At:     ${new Date().toISOString()}`,
    `Generated By:     ${input.generatedBy.username} (Role: ${input.generatedBy.role})`,
    `Scope:            ${input.scope}${input.siteName ? ` — ${input.siteName}` : ''}`,
    `Period:           ${input.period.label} (${input.period.preset})`,
    `Reports Included: ${input.reports.length} report types (${pdfCount} PDFs, ${excelCount} Excel workbooks)`,
    '',
    '--------------------------------------------------------------------------------',
    'DIRECTORY STRUCTURE & CONTENTS',
    '--------------------------------------------------------------------------------',
    '- manifest.json   : Machine-readable JSON metadata describing archive properties',
    '- reports/        : Analytical PDF presentation documents & formatted Excel sheets',
    '- README.txt      : This reference guide',
    '',
    '--------------------------------------------------------------------------------',
    'SECURITY & DATA INTEGRITY NOTICE',
    '--------------------------------------------------------------------------------',
    'This archive contains verified, presentation-grade analytical business reports.',
    'It contains ZERO raw database JSON datasets, ZERO database binary snapshots,',
    'and ZERO security credentials, tokens, or password hashes.',
    '================================================================================',
  ];
  const readmeBuffer = Buffer.from(readmeLines.join('\r\n'), 'utf-8');
  zip.file('README.txt', readmeBuffer);
  const readmeSha256 = crypto.createHash('sha256').update(readmeBuffer).digest('hex');
  fileEntries.push({
    path: 'README.txt',
    format: 'TXT',
    bytes: readmeBuffer.length,
    sha256: readmeSha256,
  });

  const packageChecksum = crypto.createHash('sha256').update(fileEntries.map(f => f.sha256 || '').join(':')).digest('hex');

  // Metadata-only manifest
  const manifest = {
    packageType: 'REPORT_PACKAGE',
    application: 'SITE WORK Enterprise System',
    exportVersion: 1,
    generatedAt: new Date().toISOString(),
    generatedBy: input.generatedBy,
    scope: {
      type: input.scope,
      siteId: input.siteId,
      siteName: input.siteName,
      siteCode: input.siteCode,
    },
    period: input.period,
    reportCount: input.reports.length,
    pdfCount,
    excelCount,
    reports: input.reports.map((r) => ({
      reportType: r.reportType,
      title: r.title,
      hasPdf: !!r.pdfBuffer,
      hasExcel: !!r.excelBuffer,
    })),
    packageChecksum,
    files: fileEntries,
  };
  const manifestBuffer = Buffer.from(JSON.stringify(manifest, null, 2), 'utf-8');
  zip.file('manifest.json', manifestBuffer);

  // Invariant security checks: Assert NO database files or raw JSON datasets
  const allPaths = Object.keys(zip.files);
  const hasDb = allPaths.some((p) => p.toLowerCase().endsWith('.db') || p.toLowerCase().endsWith('.sqlite'));
  if (hasDb) {
    throw new Error('SECURITY VIOLATION: Database snapshot file detected in Report ZIP.');
  }
  const hasRawJson = allPaths.some((p) => p.startsWith('data/'));
  if (hasRawJson) {
    throw new Error('SECURITY VIOLATION: Raw entity JSON dump detected in Report ZIP.');
  }

  return await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

/**
 * Creates an in-memory ZIP package containing the generated export artifacts,
 * machine-readable manifest.json, and explanatory README.txt.
 */
export async function createCompleteExportZip(input: ZipPackageInput): Promise<Buffer> {
  const zip = new JSZip();
  const fileEntries: ManifestFileEntry[] = [];

  // 1. JSON Data file (legacy/internal only if explicitly passed)
  if (input.jsonBuffer) {
    const jsonPath = `data/${input.baseName}.json`;
    zip.file(jsonPath, input.jsonBuffer);
    fileEntries.push({
      path: jsonPath,
      format: 'JSON',
      bytes: input.jsonBuffer.length,
    });
  }

  // 2. PDF Document
  if (input.pdfBuffer) {
    const pdfPath = `pdf/${input.baseName}.pdf`;
    zip.file(pdfPath, input.pdfBuffer);
    fileEntries.push({
      path: pdfPath,
      format: 'PDF',
      bytes: input.pdfBuffer.length,
    });
  }

  // 3. Excel Spreadsheet
  if (input.excelBuffer) {
    const excelPath = `excel/${input.baseName}.xlsx`;
    zip.file(excelPath, input.excelBuffer);
    fileEntries.push({
      path: excelPath,
      format: 'XLSX',
      bytes: input.excelBuffer.length,
    });
  }

  // 4. README.txt
  const readmeContent = generateReadmeText(input.manifest);
  const readmeBuffer = Buffer.from(readmeContent, 'utf-8');
  zip.file('README.txt', readmeBuffer);
  fileEntries.push({
    path: 'README.txt',
    format: 'TXT',
    bytes: readmeBuffer.length,
  });

  // 5. Update and attach manifest.json
  const finalizedManifest: ExportManifest = {
    ...input.manifest,
    files: fileEntries,
  };
  const manifestBuffer = Buffer.from(JSON.stringify(finalizedManifest, null, 2), 'utf-8');
  zip.file('manifest.json', manifestBuffer);

  // Generate binary buffer
  return await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });
}

function generateReadmeText(manifest: ExportManifest): string {
  const lines: string[] = [
    '================================================================================',
    'AB CONSTRUCTIONS & INTERIORS — SITE WORK ENTERPRISE ARCHIVE',
    '================================================================================',
    '',
    `Application:      ${manifest.application}`,
    `Export Type:      ${manifest.exportType}`,
    `Generated At:     ${manifest.generatedAt}`,
    `Generated By:     ${manifest.generatedBy.username} (Role: ${manifest.generatedBy.role})`,
    `Scope:            ${manifest.scope.type} ${manifest.scope.siteName ? `— ${manifest.scope.siteName}` : ''}`,
    `Period:           ${manifest.period.label} (${manifest.period.preset})`,
    '',
    '--------------------------------------------------------------------------------',
    'ARCHIVE CONTENTS & DIRECTORY STRUCTURE',
    '--------------------------------------------------------------------------------',
    '- manifest.json   : Machine-readable JSON metadata describing archive properties',
    '- data/           : Structured JSON data payload with canonical numeric metrics',
    '- pdf/            : Consolidated multi-section presentation PDF document',
    '- excel/          : Multi-sheet enterprise workbook with formulas & KPI strips',
    '- README.txt      : This reference guide',
    '',
    '--------------------------------------------------------------------------------',
    'DATA INTEGRITY & SECURITY POLICY',
    '--------------------------------------------------------------------------------',
    'This export was generated by an authenticated session in compliance with',
    'enterprise access control policies (RBAC). All monetary figures are recorded',
    'both in precise subunit currency (paise) and formatted Indian Rupees (INR).',
    'No sensitive secrets, cryptographic keys, or password hashes are contained',
    'within this archive.',
    '',
    '================================================================================',
  ];

  return lines.join('\r\n');
}
